### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by egrish** [twilio/flex-ui-sample#1]
When running locally the flex ui, there is an error:

Failed to load resource: the server responded with a status of 403 ()
:1 Failed to load https://flex.twilio.com/plugins?roles=agent&serviceBaseUrl=http:%2F%2Flocalhost:8080%2F&version=1.0.1: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
index.js:1452 failed to reach plugin service at https://flex.twilio.com/plugins Error: Network Error
    at createError (createError.js:17)
    at XMLHttpRequest.handleError (xhr.js:87)

**Comment by madisabel** [comment]
Hi, is this consistently happening for you? If so, could you please contact @MartinAmps privately to investigate.

**Comment by Speedrookie** [comment]
Also having this issue, looking into CORS...
