### ISSUE TITLE
error Couldn't find package "@twilio/frame-ui@^0.23.1" required by "@twilio/flex-ui@^1" on the "npm" registry

### ISSUE THREAD

**Issue by julianfrank** [twilio/flex-ui-sample#10]
error Couldn't find package "@twilio/frame-ui@^0.23.1" required by "@twilio/flex-ui@^1" on the "npm" registry.

**Comment by isaacnass** [comment]
Don't use yarn, you have to do an `npm install`

**Comment by TheUrbina20** [comment]
Is there a reason why the package is not on yarn registry?
I don't understand why this issue is closed.
