### ISSUE TITLE
Not Found: @twilio/frame-ui@^0.16.0

### ISSUE THREAD

**Issue by erperejildo** [twilio/flex-ui-sample#7]
I'm asking here because I have no idea where to ask...

I'm working on an "old" projects which was using `frame-ui` package and I'm getting this error:
`npm ERR! 404 Not Found: @twilio/frame-ui@^0.16.0`

I think (as far as I know) that I should move to this new package: https://www.npmjs.com/package/@twilio/flex-ui
but it has `frame-ui` as a dependency as well as `@twilio/twilio-flex-insights`, which also gives me an error.

What should I use?

**Comment by ChristianDavis** [comment]
a number of the docs refer to @twilio/frame-ui, and that doesn't seem to be a live package
https://www.twilio.com/docs/flex/supervisor-desktop-agents-data-table-and-call-monitoring#add-columns-to-agentdatatable

**Comment by ChristianDavis** [comment]
@erperejildo actually frame-ui is installed internally to flex-ui, and all its components are exported through the flex-ui package. So if you remove frame-ui from your deps, and then take any components you need from flex-ui, that seems to working for me. e.g.
```
import { ColumnDefinition } from "@twilio/frame-ui";
import { TaskCardList } from "@twilio/flex-ui";
```
becomes
```
import { TaskCardList, ColumnDefinition } from "@twilio/flex-ui";
```

**Comment by erperejildo** [comment]
ok, @ChristianDavis, I'll try that. Thanks!
